version: '3.8'

services:
  postgresql:
    image: postgres:14.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fastapi-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2.7
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  rabbitmq:
    image: rabbitmq:3.9.7
    ports:
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit
      - RABBITMQ_DEFAULT_PASS=password


  web:
    build: ./backend
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn core.server:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
      - ./backend/campaigns:/app/campaigns
    env_file:
      - ./backend/.env
    depends_on:
      - postgresql
      - redis
      - rabbitmq

  # atlas-planner-frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   env_file:
  #     - ./frontend/.env
  #   depends_on:
  #     - web  # optional: if frontend needs backend ready first

volumes:
  pgdata:
  redis:
