/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CampaignResponse
 */
export interface CampaignResponse {
    /**
     * 
     * @type {string}
     * @memberof CampaignResponse
     */
    campaignName: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignResponse
     */
    folderPath: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignResponse
     */
    startDate: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignResponse
     */
    durationDays: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignResponse
     */
    jsonFilePath?: string;
}
