/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssignedResource } from './assigned-resource';
/**
 * 
 * @export
 * @interface CampaignDetailResponse
 */
export interface CampaignDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof CampaignDetailResponse
     */
    campaignName: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignDetailResponse
     */
    folderPath: string;
    /**
     * 
     * @type {string}
     * @memberof CampaignDetailResponse
     */
    startDate: string;
    /**
     * 
     * @type {number}
     * @memberof CampaignDetailResponse
     */
    durationDays: number;
    /**
     * 
     * @type {string}
     * @memberof CampaignDetailResponse
     */
    jsonFilePath?: string;
    /**
     * 
     * @type {Array<AssignedResource>}
     * @memberof CampaignDetailResponse
     */
    assignedPeople?: Array<AssignedResource>;
    /**
     * 
     * @type {Array<AssignedResource>}
     * @memberof CampaignDetailResponse
     */
    assignedEquipment?: Array<AssignedResource>;
    /**
     * 
     * @type {Array<AssignedResource>}
     * @memberof CampaignDetailResponse
     */
    assignedSensors?: Array<AssignedResource>;
}
