/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryEquipmentResponse } from './category-equipment-response';
import { CategoryPersonResponse } from './category-person-response';
/**
 * 
 * @export
 * @interface CategoryResponse
 */
export interface CategoryResponse {
    /**
     * 
     * @type {number}
     * @memberof CategoryResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryResponse
     */
    name: string;
    /**
     * 
     * @type {Array<CategoryPersonResponse>}
     * @memberof CategoryResponse
     */
    people?: Array<CategoryPersonResponse>;
    /**
     * 
     * @type {Array<CategoryEquipmentResponse>}
     * @memberof CategoryResponse
     */
    equipment?: Array<CategoryEquipmentResponse>;
}
