/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryEquipmentCreateRequest } from './category-equipment-create-request';
import { CategoryPersonCreateRequest } from './category-person-create-request';
/**
 * 
 * @export
 * @interface CategoryUpdateRequest
 */
export interface CategoryUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof CategoryUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {Array<CategoryPersonCreateRequest>}
     * @memberof CategoryUpdateRequest
     */
    people?: Array<CategoryPersonCreateRequest>;
    /**
     * 
     * @type {Array<CategoryEquipmentCreateRequest>}
     * @memberof CategoryUpdateRequest
     */
    equipment?: Array<CategoryEquipmentCreateRequest>;
}
