/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EquipmentResponse } from './equipment-response';
/**
 * 
 * @export
 * @interface CategoryEquipmentResponse
 */
export interface CategoryEquipmentResponse {
    /**
     * 
     * @type {number}
     * @memberof CategoryEquipmentResponse
     */
    equipmentId: number;
    /**
     * 
     * @type {EquipmentResponse}
     * @memberof CategoryEquipmentResponse
     */
    equipment?: EquipmentResponse;
}
