/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PeopleResponse } from './people-response';
/**
 * 
 * @export
 * @interface CategoryPersonResponse
 */
export interface CategoryPersonResponse {
    /**
     * 
     * @type {number}
     * @memberof CategoryPersonResponse
     */
    peopleId: number;
    /**
     * 
     * @type {PeopleResponse}
     * @memberof CategoryPersonResponse
     */
    person?: PeopleResponse;
}
