/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EquipmentCreateRequest
 */
export interface EquipmentCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    manufacturer: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    serialNumber: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    location: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentCreateRequest
     */
    notes?: string;
}
