/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface EquipmentUpdateRequest
 */
export interface EquipmentUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    manufacturer?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    serialNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof EquipmentUpdateRequest
     */
    notes?: string;
}
