/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryResponse } from './category-response';
/**
 * 
 * @export
 * @interface ModuleTestsTestSchemaResponseTestResponse
 */
export interface ModuleTestsTestSchemaResponseTestResponse {
    /**
     * 
     * @type {number}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    safety?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    maps?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    simulation?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    summary?: string;
    /**
     * 
     * @type {Array<CategoryResponse>}
     * @memberof ModuleTestsTestSchemaResponseTestResponse
     */
    categories?: Array<CategoryResponse>;
}
