/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModuleProjectProjectSchemaResponseTestResponse
 */
export interface ModuleProjectProjectSchemaResponseTestResponse {
    /**
     * 
     * @type {number}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    adminId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    peopleId?: number;
    /**
     * 
     * @type {number}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    equipmentId?: number;
    /**
     * 
     * @type {string}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    safety?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    maps?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    simulation?: string;
    /**
     * 
     * @type {string}
     * @memberof ModuleProjectProjectSchemaResponseTestResponse
     */
    summary?: string;
}
