/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PeopleUpdateRequest
 */
export interface PeopleUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    role?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleUpdateRequest
     */
    calendarIntegrationId?: string;
}
