/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PeopleResponse
 */
export interface PeopleResponse {
    /**
     * 
     * @type {number}
     * @memberof PeopleResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof PeopleResponse
     */
    calendarIntegrationId?: string;
}
