/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectCreateResponse
 */
export interface ProjectCreateResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectCreateResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateResponse
     */
    subtitle?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreateResponse
     */
    date: Date;
}
