/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProjectCreateRequest
 */
export interface ProjectCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    subtitle?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateRequest
     */
    projectType?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreateRequest
     */
    date?: Date;
}
