/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModuleProjectProjectSchemaResponseTestResponse } from './module-project-project-schema-response-test-response';
/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    subtitle?: string;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    date: Date;
    /**
     * 
     * @type {Array<ModuleProjectProjectSchemaResponseTestResponse>}
     * @memberof ProjectResponse
     */
    tests?: Array<ModuleProjectProjectSchemaResponseTestResponse>;
}
