/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryUpdateRequest } from './category-update-request';
/**
 * 
 * @export
 * @interface TestUpdateRequest
 */
export interface TestUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof TestUpdateRequest
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof TestUpdateRequest
     */
    safety?: string;
    /**
     * 
     * @type {string}
     * @memberof TestUpdateRequest
     */
    maps?: string;
    /**
     * 
     * @type {string}
     * @memberof TestUpdateRequest
     */
    simulation?: string;
    /**
     * 
     * @type {string}
     * @memberof TestUpdateRequest
     */
    summary?: string;
    /**
     * 
     * @type {Array<CategoryUpdateRequest>}
     * @memberof TestUpdateRequest
     */
    categories?: Array<CategoryUpdateRequest>;
}
