/* tslint:disable */
/* eslint-disable */
/**
 * Atlas Planner Backend
 * Atlas Planner Backend by @zisan
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryCreateRequest } from './category-create-request';
/**
 * 
 * @export
 * @interface TestCreateRequest
 */
export interface TestCreateRequest {
    /**
     * 
     * @type {number}
     * @memberof TestCreateRequest
     */
    projectId: number;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    tags?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    safety?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    maps?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    simulation?: string;
    /**
     * 
     * @type {string}
     * @memberof TestCreateRequest
     */
    summary?: string;
    /**
     * 
     * @type {Array<CategoryCreateRequest>}
     * @memberof TestCreateRequest
     */
    categories?: Array<CategoryCreateRequest>;
}
